"""
Algorithm 6: Structured AI Report Generator
===========================================
Formats multi-modal AI behavioral screening findings into clinical reports,
including per-model breakdowns, evidence summaries, domain indicators, and disclaimers.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from app.services.ai.contracts import FusionResult


DISCLAIMER_TEXT = (
    "CLINICAL NOTICE & MEDICAL DISCLAIMER: This AI-assisted screening report is generated by an "
    "automated multi-modal behavioral analysis pipeline for early developmental screening and observation. "
    "It DOES NOT constitute a formal medical, neurological, or psychiatric diagnosis of Autism Spectrum Disorder (ASD). "
    "Please consult a certified developmental pediatrician, pediatric neurologist, or licensed child psychologist."
)


class AIReportGenerator:
    @staticmethod
    def build_report_data(
        fusion_result: FusionResult,
        child_id: Optional[int] = None,
        child_name: Optional[str] = None,
        child_age: Optional[int] = None,
        child_gender: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Builds a comprehensive structured clinical screening report dictionary.
        """
        now_iso = datetime.now(timezone.utc).isoformat()

        report = {
            "report_metadata": {
                "generated_at": now_iso,
                "pipeline_version": "2.0.0-fusion",
                "disclaimer": DISCLAIMER_TEXT,
            },
            "child_profile": {
                "child_id": child_id,
                "name": child_name or "Child Profile",
                "age": child_age,
                "gender": child_gender,
            },
            "video_metadata": fusion_result.video_metadata,
            "screening_estimate": {
                "behavioral_screening_indicator": fusion_result.percentage,
                "confidence_score": fusion_result.confidence_score,
                "support_level": fusion_result.support_indicator,
                "summary": fusion_result.summary,
            },
            "models": fusion_result.models,
            "domain_breakdown": fusion_result.domain_breakdown,
            "raw_metrics": fusion_result.raw_model_metrics,
            "therapist_recommendations": fusion_result.therapist_recommendations,
            "general_recommendations": fusion_result.recommendations,
            "timing": fusion_result.timing,
        }
        return report
